travis:
  secure:
    BINSTAR_TOKEN: KTiofRbM4B7ja4lZwUuHlpVhFVbWcmAJjB/WZc1QKTXPd/XVKsuu2xQYCaiyFovVDuh7iES0jhuOnM9Tc1eLQgY5VTeoMkmSKon/S5Z0zZiBxoXM2W1kP5A24hQN9yoXpNy/QlVEdxaLWAhV4/2Mc7LXHHIacZKptre1MI7SShm1GoY21SBQXoHz2HrjJUJtJOCmPN6Q4AxErhya3u/AJijQQU7ENVuIqZtyfvqhdC7CQqlg9+3GM2ok2eq0NXqt2MsivZpwc+/m9nq/3fOQ5PPpxwpOFbYq1RARbz4HDXwAyHbVq0YylCPXFteAOIhWpkKZ/MWyaM9wTfINUTvmMZ9AUnvgPqZBJhy2FGuG6L2gLPWK86b8lk2UMGzPDsebQMrfusQvDQ09CL2IDWwS5TKOUspZoxt8cgUY3X5WWo2s0q83FMS46MS59r4IlEjX0Z79NZMjapvlHQ995gkNNtpal1Vsl19goSYKFb85zS0iwv/mYvKDuaDnE1vWSNeW0DFOtG3VYYllbzqrMywNGOTgc4nTSjiF9P6MeMXsVeQaPNHupayYjzFXeLJSNSDJkzrT2NYRB3XB5ZrKLt9aYMpfM+dISYT54gI0uttDE9lRbmURkGDa91/MnrTMpbgnzEX7j0Ob5pe/VQeCKXMFxgfnptRBGcax5518tV6oHNc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
