travis:
  secure:
    BINSTAR_TOKEN: AIlaBklLuwxI83xz1hPnZIc9wnRfwHtsXX93BN6wz3wmLK0QLqZc16Tl+/irQW28aGytCF7mULKcFGOACl5u6VT4MmJuuLNm4vrZp32z71bs4YDbz+vYXB6ixt/Zz0NNzCvemJURvyWfYW8Qz6LWqrQTUVgjMnC6DCOnWicOknn5qCr8hSjoOyKPw/qSJ9or9Vikn7MQOTYe8WnbjNwcPoDHSA2CgYkQSYY9uiF637vE5qCMvF1a7H6w+rV7hXIoZsstHaQctbhQ3HxbVvvChZPqcQJSN3Ls520VRsRKV5xCwd+v6qLMGVc1SJkmjbravvXfkyfbXxCTtPKXVAbAItv/nbyHaTJXIAmRQCSe9RddXJNuz6Jp95XEpQsxkfH+i1OSgKU1rD7cKM09HR3fAFXLJGbeqA9p/seZQYUXDmzJqa6v0zaoheQfhKiHhRsgZVaxwnMTuyevfWC+4xqFME01bf3MpGcoiHRQhESt5AfPYxPb+rNPJ4LqGjbuOZrMrY5IhfVAE6FgiNmDP4JBFATft4/B1TZHGt9VSgGOSujZUP/XmrU5FhOJs+XJvFvy91RwXGKSdDXqBV3OHTGCEOvwV+Jz0ZIleVR4Q38n+viTY20KIvX6HJ8Xx4G/eYs2NSvchQr5v7+hndCv2tMorthXtgqquwkN/fXRx5POCSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
